In [5]:
import glob
import tensorflow as tf
# # from tensorflow.python.ops import control_flow_ops
# from tqdm import tqdm
from progressbar import ProgressBar
import h5py
import matplotlib.pyplot as plt
from natsort import natsorted

I=0
def _parse_function(example_proto):
    print('1')
    features = {"X": tf.FixedLenFeature((257), tf.float32),
              "Y": tf.FixedLenFeature((257), tf.float32)}
    parsed_features = tf.parse_single_example(example_proto, features)
    print("i was here")
    print('2')
    return parsed_features["X"], parsed_features["Y"]

def rbm_layer(n_visible, n_hidden, num_epochs, num_cases, lr, lrh, ws, bs, layer_n, len_data, directories):
    Data_path = directories[0]
    tfrecord_folder_parent = directories[1]
    tfrecord_folder = directories[2]
    
    tfrecord_path_x = os.path.normpath(os.path.join(Data_path,tfrecord_folder_parent,tfrecord_folder))
    sorted_names_x = natsorted(os.listdir(tfrecord_path_x))
    trainfilenames_x = []
    for i in sorted_names_x:
        trainfilenames_x.append(os.path.normpath(os.path.join(tfrecord_path_x,i)))
#     filenames_x = tf.placeholder(tf.string, shape=[None])
#     dataset_x = tf.data.TFRecordDataset(filenames_x)
    dataset_x = tf.data.TFRecordDataset(trainfilenames_x)
    dataset_x = dataset_x.map(_parse_function)  # Parse the record into tensors.
#     dataset_x = dataset_x.repeat()  # Repeat the input indefinitely.
    dataset_x = dataset_x.batch(num_cases)
#     iterator_x = dataset_x.make_initializable_iterator()
    
    weightcost  = 0.0002
    initialmomentum  = 0.5
    finalmomentum    = 0.9
    numcases = 128
    W_adder  = tf.zeros((n_visible,n_hidden),dtype=tf.dtypes.float32)
    bh_adder = tf.zeros((1,n_hidden),dtype=tf.dtypes.float32)
    bv_adder = tf.zeros((1,n_visible),dtype=tf.dtypes.float32)
    
    W  = tf.Variable(tf.random_normal([n_visible, n_hidden], mean=0, stddev=0.01), name="W") #The weight matrix that stores the edge weights
    bh = tf.Variable(tf.zeros([1, n_hidden],  tf.float32, name="bh")) #The bias vector for the hidden layer
    bv = tf.Variable(tf.zeros([1, n_visible],  tf.float32, name="bv")) #The bias vector for the visible layer

    def sample(probs):
        #Takes in a vector of probabilities, and returns a random vector of 0s and 1s sampled from the input vector
#         return tf.floor(probs + tf.random_uniform(tf.shape(probs), 0, 1))
        return tf.cast(probs > tf.random_uniform(tf.shape(probs), 0, 1),tf.float32)
        
    count=0
    pbar = ProgressBar()
    for epoch in pbar(range(num_epochs)):
        count+=1
        incount=0
        errsum = 0
        for x in dataset_x:

                    
            poshidprobs = tf.sigmoid(tf.matmul(x[0], W) + bh) #Propagate the visible values to sample the hidden values
            poshidstates = sample(poshidprobs)
            #128*512
            #Next, we update the values of W, bh, and bv, based on the difference between the samples that we drew and the original values
            posprods  = tf.matmul(tf.transpose(x[0]),poshidprobs) #771*512
            poshidacts = tf.reduce_sum(poshidprobs, axis=0) #(512)
#             print(poshidprobs)
#             print(poshidacts.numpy())
            posvisacts = tf.reduce_sum(x[0],axis=0)#771
            
            negdata   = tf.sigmoid(tf.matmul(poshidstates, tf.transpose(W)) + bv)#128*711
            neghidprobs   = tf.sigmoid(tf.matmul(negdata, W) + bh) #128*512
            negprods  = tf.matmul(tf.transpose(negdata),neghidprobs); #771*512##################################
            neghidacts = tf.reduce_sum(neghidprobs, axis=0)
            negvisacts = tf.reduce_sum(negdata, axis=0)
            
            if incount%100==0:
                print(incount)
            incount+=1
            if epoch>5:
                m=finalmomentum
            else:
                m=initialmomentum
#             [posprods,negprods,posvisacts,negvisacts,poshidacts,neghidacts] = gibbs_step(x[0])
            W_adder = (m * W_adder)+ (lr*(posprods-negprods)/numcases)-(weightcost*W)
            bv_adder = (m * bv_adder)+ ((lrh/numcases)*(posvisacts-negvisacts))
            bh_adder = (m * bh_adder)+ ((lrh/numcases)*(poshidacts-neghidacts))
#             print(posprods)
#             print(poshidacts-neghidacts)
#             print(bv_adder)
            #When we do sess.run(updt), TensorFlow will run all 3 update steps
            updt = [W.assign_add(W_adder).numpy(), bv.assign_add(bv_adder).numpy(), bh.assign_add(bh_adder).numpy()] 
            err= tf.reduce_sum(tf.reduce_sum((x[0]-negdata)**2 ,axis =0),axis=0)
            errsum = err + errsum;
        print(errsum)
#         print(count)
    return updt




In [7]:
# import libraries.
import numpy as np
from sklearn.utils import shuffle
import tensorflow as tf
import datetime
tf.enable_eager_execution()
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import layers
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor
# import keras
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras import optimizers
from tensorflow.keras import regularizers

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error
from pystoi.stoi import stoi
import h5py
import sys
######################
#import libraries.
import matplotlib.pyplot as plt
from tabulate import tabulate
import time
import os
import librosa
from librosa.core import stft, istft
####import sounddevice as sd
import time
print('imported')
# #######################
Data_path = 'D:/studies/university/thesis/speech_separation_codes/du16/donesomestuff'
# Data_path = os.getcwd()
tfrecord_folder_parent = 'tfrecord_files'
tfrecord_folder = 'mixed_10h_norm2'
tfrecord_val_folder = 'validation_norm_small'
ckpt_folder = '5'
dirs = [Data_path, tfrecord_folder_parent, tfrecord_folder]
 
# len_data = (684108, 257)
# len_data = (2197278, 257)
# val_len = (97278,257)
len_data = (200000, 257)
val_len = (100000,257)
w=3
h = [512]
global batch_size
batch_size = 128
#######################
#define reconstruct function to reconstruct sound from framed signal.
def reconstruct(wave,angle):
    recon = np.sqrt(np.power(10, wave))
    recon1 = recon*np.cos(angle)+recon*np.sin(angle)*1j
    recon = librosa.core.istft((recon1.T), hop_length=256, win_length=512, window='hann')
    return recon

########################
# visible = w*len_data[1]
visible = len_data[1]
hidden = h[0]
# visible1 = h[0]
# hidden1 = h[1]
# visible2 = h[1]
# hidden2 = len_data[1]

layer1 = rbm_layer(visible, hidden, 10, batch_size, 0.1, 0.1, [np.eye(visible,hidden)], [np.zeros((1,visible))], 1, len_data[0],dirs)
# layer2 = rbm_layer(visible1, hidden1, 50, batch_size, 0.01, [np.eye(visible,hidden),layer1[0]], [np.zeros((1,visible)),layer1[2]], 2, len_data[0], dirs)
# layer3 = rbm_layer(visible2, hidden2, 50, batch_size, 0.01, [np.eye(visible),layer1[0],layer2[0]], [np.zeros((1,visible)),layer1[2],layer2[2]], 3, len_data[0], dirs)

###############################
#######################
# I=0

# # epochs_num=50
# global datalen
# datalen=len_data[0]


# seed = 7
# rate1 = 0.1
# rate2 = 0.2
# buffersize = 1000
# from tensorflow.keras.layers import Activation
# # from keras.layers import Activation
# np.random.seed(seed)
# act1 = layers.LeakyReLU(alpha=0.1)
# model = Sequential()
# # model.add(layers.Dropout(rate1, noise_shape=None, seed=None))
# # ,kernel_regularizer=regularizers.l2(0.001)
# # model.add(Dense(h[0], input_dim = w*len_data[1]))
# model.add(Dense(h[0], input_dim = w*len_data[1], kernel_initializer= tf.constant_initializer(layer1[0]), bias_initializer = tf.constant_initializer(layer1[2])))
# # , kernel_initializer= tf.constant_initializer(layer1[0]), bias_initializer = tf.constant_initializer(layer1[2])
# # tf.constant_initializer(layer1[0])
# # tf.constant_initializer(layer1[2])
# model.add(BatchNormalization())
# # model.add(act1)
# model.add(Activation('sigmoid'))
# # act2=layers.LeakyReLU(alpha=0.1)
# # model.add(layers.Dropout(rate2, noise_shape=None, seed=None))
# # model.add(Dense(h[1]))
# # model.add(act2)
# # act3=layers.LeakyReLU(alpha=0.1)
# # # model.add(layers.Dropout(rate, noise_shape=None, seed=None))
# # model.add(Dense(h[2]))
# # model.add(act3)
# # act=layers.LeakyReLU(alpha=0.01)
# model.add(Dense(len_data[1]))
# #############################################
# import os
# from natsort import natsorted

# def _parse_function(example_proto):
#     features = {"X": tf.FixedLenFeature((3*257), tf.float32),
#               "Y": tf.FixedLenFeature((257), tf.float32)}
#     parsed_features = tf.parse_single_example(example_proto, features)
#     return parsed_features["X"], parsed_features["Y"]

# tfrecord_path = os.path.normpath(os.path.join(Data_path,tfrecord_folder_parent,tfrecord_folder))
# sorted_names = natsorted(os.listdir(tfrecord_path))
# trainfilenames = []
# for i in sorted_names:
#     trainfilenames.append(os.path.normpath(os.path.join(tfrecord_path,i)))
# # filenames = tf.placeholder(tf.string, shape=[None])
# # dataset = tf.data.TFRecordDataset(filenames)
# dataset = tf.data.TFRecordDataset(trainfilenames)
# dataset = dataset.map(_parse_function)  # Parse the record into tensors.
# dataset = dataset.repeat()  # Repeat the input indefinitely.
# dataset = dataset.batch(batch_size)
# dataset = dataset.shuffle(buffersize)
# # iterator = dataset.make_initializable_iterator()

# tfrecord_path_val = os.path.normpath(os.path.join(Data_path,tfrecord_folder_parent,tfrecord_val_folder))
# sorted_names_val = natsorted(os.listdir(tfrecord_path_val))
# trainfilenames_val = []
# for i in sorted_names_val:
#     trainfilenames_val.append(os.path.normpath(os.path.join(tfrecord_path_val,i)))
# # filenames_val = tf.placeholder(tf.string, shape=[None])
# # dataset_val = tf.data.TFRecordDataset(filenames_val)
# dataset_val = tf.data.TFRecordDataset(trainfilenames_val)
# dataset_val = dataset_val.map(_parse_function)  # Parse the record into tensors.
# dataset_val = dataset_val.repeat()  # Repeat the input indefinitely.
# dataset_val = dataset_val.batch(128)
# # iterator_val = dataset_val.make_initializable_iterator()

# epochs_num = 50
# steps = len_data[0] // batch_size
# val_steps = val_len[0] // batch_size
# # You can feed the initializer with the appropriate filenames for the current
# # phase of execution, e.g. training vs. validation.
# # next_elem = iterator_val.get_next()
# # Initialize `iterator` with training data.

# if not os.path.exists(os.path.join(Data_path,"checkpoints",ckpt_folder)):
#     os.makedirs(os.path.join(Data_path,"checkpoints",ckpt_folder))

# print(datetime.datetime.now())
# # with tf.Session() as sess:
# #     sess.run(tf.global_variables_initializer())
# #     sess.run(iterator.initializer, feed_dict={filenames: trainfilenames})
# #     sess.run(iterator_val.initializer, feed_dict={filenames_val: trainfilenames_val})
# print("initialized")
# checkpoint_path = os.path.normpath(os.path.join(Data_path,"checkpoints",ckpt_folder,"weights.{epoch:02d}.hdf5"))
# checkpoint_dir = os.path.dirname(checkpoint_path)

# cp_callback = tf.keras.callbacks.ModelCheckpoint(
#     checkpoint_path, verbose=1, save_best_only=True, save_weights_only=True)
#         # Save weights, every 5-epochs.
# #         period=1)
# early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=30)
# # opt = tf.keras.optimizers.Adamax()
# # opt = tf.train.AdamOptimizer()
# opt = tf.keras.optimizers.SGD()
# model.compile(loss='mean_squared_error', optimizer=opt)
# history = model.fit( dataset, steps_per_epoch=steps,epochs=epochs_num, callbacks = [cp_callback,early_stop], verbose=1,validation_data=dataset_val,validation_steps=val_steps)
# #     model.save(os.path.normpath(os.path.join(Data_path, 'models', "model_3h_dataset.h5")))
# #     tf.keras.models.save_model(model, os.path.normpath(os.path.join(Data_path, 'models', "model_3h_dataset.h5")))
# #     model.save_weights(os.path.normpath(os.path.join(Data_path, 'models', "model_3h_dataset.h5")))
# model_json = model.to_json()
# with open(os.path.normpath(os.path.join(Data_path, 'models', "model_"+ckpt_folder+".json")), "w") as json_file:
#     json_file.write(model_json)
# # # serialize weights to HDF5
# model.save_weights(os.path.normpath(os.path.join(Data_path, 'models', "model_"+ckpt_folder+".h5")))
# print("Saved model to disk")
    
# print(datetime.datetime.now())
# %matplotlib inline
# # summarize history for loss
# plt.plot(history.history['loss'])
# plt.plot(history.history['val_loss'])
# plt.title('model loss')
# plt.ylabel('loss')
# plt.xlabel('epoch')
# plt.legend(['train'], loc='upper left')
# plt.show()
# plt.savefig(os.path.normpath(os.path.join(Data_path,'images',ckpt_folder+'.png')))
# # model_json = model.to_json()
# # with open("model_10h_dataset.json", "w") as json_file:
# #     json_file.write(model_json)
# # model.save_weights("model_10h_dataset.h5")
# # print("Saved model to disk")


imported
1
i was here
2
0
100
200
300
400
500
600
700


tf.Tensor(25459236.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25877740.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25886400.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25888386.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25889182.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25889560.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25871744.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25891428.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25891570.0, shape=(), dtype=float32)
0
100
200
300
400
500
600
700


tf.Tensor(25891606.0, shape=(), dtype=float32)


In [17]:
np.savetxt(os.path.normpath(os.path.join(Data_path,'results','rbm','test','layers10.txt')),layer1[0])
np.savetxt(os.path.normpath(os.path.join(Data_path,'results','rbm','test','layers11.txt')),layer1[1])
np.savetxt(os.path.normpath(os.path.join(Data_path,'results','rbm','test','layers12.txt')),layer1[2])

In [1]:
write_path = 'D:/studies/university/thesis/speech_separation_codes/du16/donesomestuff/10hdata'
mixed_folder = os.path.normpath(os.path.join(write_path,'mixed_log_10h_norm2'))
h5f = h5py.File(mixed_folder+'.hdf5','r')
ftr = h5f['mixed_log_10h_norm2'][0:126]
h5f.close()
mixed_folder = os.path.normpath(os.path.join(write_path,'mixed_phase_10h_nozeroinsert'))
h5f = h5py.File(mixed_folder+'.hdf5','r')
ftr_phase = h5f['mixed_phase_10h_nozeroinsert'][0:126]
h5f.close()

NameError: name 'os' is not defined

In [16]:
hidden1 = np.matmul(ftr,layer1[0])+layer1[2]
# hidden2 = np.matmul(hidden1,layer2[0])+layer2[2]
# hidden3 = np.matmul(hidden2,layer3[0])+layer3[2]
hidden1_b = np.matmul(hidden1,layer1[0].T)+layer1[1]
# hidden2_b = np.matmul(hidden3_b,layer2[0].T)+layer2[1]
# hidden1_b = np.matmul(hidden2_b,layer1[0].T)+layer1[1]

In [39]:
((np.ones((300,257))-mean)/std)*std+mean

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [38]:
std

array([1.53837216, 1.32554345, 1.46483478, 1.73449735, 1.78078742,
       1.79493836, 1.91780831, 1.95251315, 1.86977405, 1.77915561,
       1.76519178, 1.86027562, 1.96966473, 1.99097837, 1.95238138,
       1.94580237, 1.95707608, 1.92973856, 1.93212023, 1.93764876,
       1.89617586, 1.8539489 , 1.8376548 , 1.82487941, 1.77231266,
       1.74453302, 1.71202875, 1.68147863, 1.67128448, 1.65948598,
       1.66315731, 1.70590532, 1.71562715, 1.68648245, 1.65367047,
       1.62804796, 1.63988119, 1.67398255, 1.68546989, 1.67245087,
       1.66041666, 1.63824927, 1.64779135, 1.65841155, 1.6545928 ,
       1.64101815, 1.66718663, 1.65744804, 1.63700542, 1.61295695,
       1.62263098, 1.61948365, 1.64646589, 1.65286744, 1.62544737,
       1.62465334, 1.63801187, 1.63111888, 1.61911113, 1.60926431,
       1.59281308, 1.61490726, 1.63060496, 1.63046297, 1.5992348 ,
       1.57998928, 1.57301462, 1.57245691, 1.59928312, 1.61450441,
       1.60943051, 1.6009857 , 1.61223461, 1.64187435, 1.64957

In [18]:
ftr

array([[ 0.28766647,  0.11526573, -0.7069241 , ..., -0.55612373,
        -0.5525803 , -0.50696164],
       [ 0.12223668,  0.26682785, -0.4372746 , ..., -0.99636066,
        -1.0043348 , -1.5150769 ],
       [ 0.8128672 ,  0.6103882 , -0.9415356 , ..., -1.1297925 ,
        -0.9657317 , -0.59864193],
       ...,
       [-4.825073  , -5.533287  , -4.9773455 , ..., -2.2312639 ,
        -2.2086217 , -1.930099  ],
       [-4.825073  , -5.533287  , -4.9773455 , ..., -2.2312639 ,
        -2.2086217 , -1.930099  ],
       [-4.825073  , -5.533287  , -4.9773455 , ..., -2.2312639 ,
        -2.2086217 , -1.930099  ]], dtype=float32)

In [19]:
hidden1_b

array([[4.40254208e+08, 5.10191392e+08, 3.74471776e+08, ...,
        1.04809747e+09, 1.04292179e+09, 9.52056960e+08],
       [4.53852896e+08, 5.25950912e+08, 3.86038240e+08, ...,
        1.08047168e+09, 1.07513408e+09, 9.81463616e+08],
       [4.37720800e+08, 5.07256640e+08, 3.72316192e+08, ...,
        1.04206726e+09, 1.03691443e+09, 9.46573568e+08],
       ...,
       [7.66589632e+08, 8.88369344e+08, 6.52044736e+08, ...,
        1.82498317e+09, 1.81597146e+09, 1.65776307e+09],
       [7.66589632e+08, 8.88369344e+08, 6.52044736e+08, ...,
        1.82498317e+09, 1.81597146e+09, 1.65776307e+09],
       [7.66589632e+08, 8.88369344e+08, 6.52044736e+08, ...,
        1.82498317e+09, 1.81597146e+09, 1.65776307e+09]], dtype=float32)

In [22]:
mean = np.loadtxt(os.path.normpath(os.path.join(write_path,'mean_mixed_log.txt')))
std = np.loadtxt(os.path.normpath(os.path.join(write_path,'std_mixed_log.txt')))
hidden1_b = hidden1_b*std+mean
recon = reconstruct(hidden1_b, ftr_phase)
import sounddevice as sd
sd.play(recon)

C:\Users\ASUS\Anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:56: RuntimeWarning: overflow encountered in power
C:\Users\ASUS\Anaconda3\envs\myenv\lib\site-packages\ipykernel_launcher.py:57: RuntimeWarning: invalid value encountered in multiply


In [24]:
hidden1_b

array([[1.04190072e+09, 8.96439668e+08, 8.03519419e+08, ...,
        2.90909786e+09, 2.93799079e+09, 3.04264144e+09],
       [1.07408323e+09, 9.24130176e+08, 8.28338054e+08, ...,
        2.99895567e+09, 3.02873527e+09, 3.13662102e+09],
       [1.03590519e+09, 8.91283117e+08, 7.98894094e+08, ...,
        2.89236042e+09, 2.92106759e+09, 3.02511729e+09],
       ...,
       [1.81420252e+09, 1.56092308e+09, 1.39911908e+09, ...,
        5.06542070e+09, 5.11573107e+09, 5.29797990e+09],
       [1.81420252e+09, 1.56092308e+09, 1.39911908e+09, ...,
        5.06542070e+09, 5.11573107e+09, 5.29797990e+09],
       [1.81420252e+09, 1.56092308e+09, 1.39911908e+09, ...,
        5.06542070e+09, 5.11573107e+09, 5.29797990e+09]])

In [12]:
a=tf.constant([1,2,3])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    label_numpy = a.eval()

NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

In [ ]:
import h5py 
import tensorflow as tf
hh = h5py.File('ftr_refrmd_10h.hdf5', 'r')
d=hh['ftr_refrmd_10h'][0]
len_data=d.shape
hh.close()
len_data

In [ ]:
file.close()

In [ ]:
x = tf.constant([True, False])
x=tf.cast(x, tf.int32)

In [ ]:
x